# Just the Docs configuration
title: React App Folder Structure Templates
description: Battle-tested, scalable folder structures for React applications
baseurl: "/react-app-folder-structure"
url: "https://ahmad2point0.github.io"

# Theme
theme: just-the-docs
color_scheme: light

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Navigation
nav_sort: case_insensitive
nav_external_links:
- title: GitHub Repository
  url: https://github.com/ahmad2point0/react-app-folder-structure
  hide_icon: false

# Footer
footer_content: "React App Folder Structure Templates is maintained by <a href=\"https://github.com/ahmad2point0\">ahmad2point0</a>."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# GitHub Pages
plugins:
- jekyll-default-layout
- jekyll-seo-tag

# Exclude files
exclude:
- node_modules/
- .sass-cache/
- .jekyll-cache/
- gemfiles/
- Gemfile
- Gemfile.lock
- vendor/

# Markdown
markdown: kramdown
highlighter: rouge

# Collections
collections:
  templates:
    output: true
    permalink: /:collection/:name/

defaults:
- scope:
    path: ""
  values:
    layout: default
- scope:
    path: "_templates"
  values:
    layout: default
    parent: Templates
